name: golang-security-action

on: [push, pull_request]

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: Ynniss/golang-security-action@fix/golang-security-action
              with:
                  CODE_PATH: "./middleware/"
