name: golang-security-action

on: [push, pull_request]

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: Ynniss/golang-security-action@v0.1.0-rc.6
              with:
                  CODE_PATH: "./middleware/"
                  CONF_PATH: "./gosec-conf.json"
